COMMONS_PATH: "./server/conf/commons.yml"
CRONCONF_PATH: "./server/conf/cronConf.yml"
ENV_PATH: "./server/conf/env.yml"
STEPS_PATH: "./server/conf/steps.yml"
COMMONS_BACKUP_PATH: "./server/conf/commons_%dd-MM-yyyy_hh-mm-ss%.yml"
CRONCONF_BACKUP_PATH: "./server/conf/cronConf_%dd-MM-yyyy_hh-mm-ss%.yml"
ENV_BACKUP_PATH: "./server/conf/env_%dd-MM-yyyy-hh-mm-ss%.yml"
